<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Contract\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThePodcastProject.Infraestructure\ThePodcastProject.Infraestructure.csproj" />
  </ItemGroup>

</Project>
